services:
  - type: web
    name: skyward
    env: python
    buildCommand: |
      echo "Starting build process..."
      
      # Install dependencies
      apt-get update
      apt-get install -y wget unzip xvfb curl
      
      # Install Chrome using snap (more reliable)
      apt-get install -y snapd
      snap install chromium
      
      # Install chromedriver
      wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_120/chromedriver_linux64.zip"
      unzip /tmp/chromedriver.zip -d /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      
      pip install -r requirements.txt
    startCommand: |
      Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
      DISPLAY=:99 gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: HEADLESS
        value: "true"
    autoDeploy: true