services:
  - type: web
    name: skyward
    env: python
    buildCommand: |
      echo "Starting build process..."
      
      # Install dependencies
      apt-get update
      apt-get install -y wget unzip xvfb curl gnupg
      
      # Install Chrome properly
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      apt-get update
      apt-get install -y google-chrome-stable
      
      # Verify Chrome installation
      google-chrome --version
      
      # Install chromedriver
      wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_120/chromedriver_linux64.zip"
      unzip /tmp/chromedriver.zip -d /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      chromedriver --version
      
      pip install -r requirements.txt
    startCommand: |
      Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
      DISPLAY=:99 gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: HEADLESS
        value: "true"
    autoDeploy: true