services:
  - type: web
    name: skyward
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: HEADLESS
        value: "true"
    autoDeploy: true